# Generated by Django 5.1.3 on 2024-11-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorReadings',
            new_name='SensorReading',
        ),
    ]
